/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaletteNewRouteImport } from './routes/palette/new'
import { Route as PalettePaletteIdRouteImport } from './routes/palette/$paletteId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaletteNewRoute = PaletteNewRouteImport.update({
  id: '/palette/new',
  path: '/palette/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PalettePaletteIdRoute = PalettePaletteIdRouteImport.update({
  id: '/palette/$paletteId',
  path: '/palette/$paletteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/templates': typeof TemplatesRoute
  '/palette/$paletteId': typeof PalettePaletteIdRoute
  '/palette/new': typeof PaletteNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/templates': typeof TemplatesRoute
  '/palette/$paletteId': typeof PalettePaletteIdRoute
  '/palette/new': typeof PaletteNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/templates': typeof TemplatesRoute
  '/palette/$paletteId': typeof PalettePaletteIdRoute
  '/palette/new': typeof PaletteNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview'
    | '/templates'
    | '/palette/$paletteId'
    | '/palette/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preview' | '/templates' | '/palette/$paletteId' | '/palette/new'
  id:
    | '__root__'
    | '/'
    | '/preview'
    | '/templates'
    | '/palette/$paletteId'
    | '/palette/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewRoute: typeof PreviewRoute
  TemplatesRoute: typeof TemplatesRoute
  PalettePaletteIdRoute: typeof PalettePaletteIdRoute
  PaletteNewRoute: typeof PaletteNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palette/new': {
      id: '/palette/new'
      path: '/palette/new'
      fullPath: '/palette/new'
      preLoaderRoute: typeof PaletteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palette/$paletteId': {
      id: '/palette/$paletteId'
      path: '/palette/$paletteId'
      fullPath: '/palette/$paletteId'
      preLoaderRoute: typeof PalettePaletteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewRoute: PreviewRoute,
  TemplatesRoute: TemplatesRoute,
  PalettePaletteIdRoute: PalettePaletteIdRoute,
  PaletteNewRoute: PaletteNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
