/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewIndexRouteImport } from './routes/preview/index'
import { Route as PreviewTemplateIdRouteImport } from './routes/preview/$templateId'
import { Route as PaletteNewRouteImport } from './routes/palette/new'
import { Route as PalettePaletteIdRouteImport } from './routes/palette/$paletteId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewTemplateIdRoute = PreviewTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => PreviewRoute,
} as any)
const PaletteNewRoute = PaletteNewRouteImport.update({
  id: '/palette/new',
  path: '/palette/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PalettePaletteIdRoute = PalettePaletteIdRouteImport.update({
  id: '/palette/$paletteId',
  path: '/palette/$paletteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/palette/$paletteId': typeof PalettePaletteIdRoute
  '/palette/new': typeof PaletteNewRoute
  '/preview/$templateId': typeof PreviewTemplateIdRoute
  '/preview/': typeof PreviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/palette/$paletteId': typeof PalettePaletteIdRoute
  '/palette/new': typeof PaletteNewRoute
  '/preview/$templateId': typeof PreviewTemplateIdRoute
  '/preview': typeof PreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview': typeof PreviewRouteWithChildren
  '/templates': typeof TemplatesRoute
  '/palette/$paletteId': typeof PalettePaletteIdRoute
  '/palette/new': typeof PaletteNewRoute
  '/preview/$templateId': typeof PreviewTemplateIdRoute
  '/preview/': typeof PreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview'
    | '/templates'
    | '/palette/$paletteId'
    | '/palette/new'
    | '/preview/$templateId'
    | '/preview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/templates'
    | '/palette/$paletteId'
    | '/palette/new'
    | '/preview/$templateId'
    | '/preview'
  id:
    | '__root__'
    | '/'
    | '/preview'
    | '/templates'
    | '/palette/$paletteId'
    | '/palette/new'
    | '/preview/$templateId'
    | '/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewRoute: typeof PreviewRouteWithChildren
  TemplatesRoute: typeof TemplatesRoute
  PalettePaletteIdRoute: typeof PalettePaletteIdRoute
  PaletteNewRoute: typeof PaletteNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/': {
      id: '/preview/'
      path: '/'
      fullPath: '/preview/'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/$templateId': {
      id: '/preview/$templateId'
      path: '/$templateId'
      fullPath: '/preview/$templateId'
      preLoaderRoute: typeof PreviewTemplateIdRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/palette/new': {
      id: '/palette/new'
      path: '/palette/new'
      fullPath: '/palette/new'
      preLoaderRoute: typeof PaletteNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palette/$paletteId': {
      id: '/palette/$paletteId'
      path: '/palette/$paletteId'
      fullPath: '/palette/$paletteId'
      preLoaderRoute: typeof PalettePaletteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PreviewRouteChildren {
  PreviewTemplateIdRoute: typeof PreviewTemplateIdRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewTemplateIdRoute: PreviewTemplateIdRoute,
  PreviewIndexRoute: PreviewIndexRoute,
}

const PreviewRouteWithChildren = PreviewRoute._addFileChildren(PreviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewRoute: PreviewRouteWithChildren,
  TemplatesRoute: TemplatesRoute,
  PalettePaletteIdRoute: PalettePaletteIdRoute,
  PaletteNewRoute: PaletteNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
